In [1]:
import pandas as pd

In [2]:
happiness_2015 = pd.read_csv("World_Happiness_2015.csv")

In [3]:
happiness_2015.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [4]:
happiness_2015[happiness_2015["Country"] == "Pakistan"]

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
80,Pakistan,Southern Asia,81,5.194,0.03726,0.59543,0.41411,0.51466,0.12102,0.10464,0.33671,3.10709

## pd.melt(dataframe , main_colls , factors)

In [6]:
main_colls = happiness_2015.columns[:5]
main_colls

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error'],
      dtype='object')

In [7]:
factors = happiness_2015.columns[5:]
factors

Index(['Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual'],
      dtype='object')

In [8]:
pd.melt(happiness_2015 , id_vars = main_colls , value_vars = factors)

,Country,Region,Happiness Rank,Happiness Score,Standard Error,variable,value
0,Switzerland,Western Europe,1,7.587,0.03411,Economy (GDP per Capita),1.39651
1,Iceland,Western Europe,2,7.561,0.04884,Economy (GDP per Capita),1.30232
2,Denmark,Western Europe,3,7.527,0.03328,Economy (GDP per Capita),1.32548
3,Norway,Western Europe,4,7.522,0.03880,Economy (GDP per Capita),1.45900
4,Canada,North America,5,7.427,0.03553,Economy (GDP per Capita),1.32629
...,...,...,...,...,...,...,...
1101,Rwanda,Sub-Saharan Africa,154,3.465,0.03464,Dystopia Residual,0.67042
1102,Benin,Sub-Saharan Africa,155,3.340,0.03656,Dystopia Residual,1.63328
1103,Syria,Middle East and Northern Africa,156,3.006,0.05015,Dystopia Residual,0.32858
1104,Burundi,Sub-Saharan Africa,157,2.905,0.08658,Dystopia Residual,1.83302
1105,Togo,Sub-Saharan Africa,158,2.839,0.06727,Dystopia Residual,1.56726

In [9]:
melt = pd.melt(happiness_2015 , id_vars = main_colls , value_vars = factors)
melt

,Country,Region,Happiness Rank,Happiness Score,Standard Error,variable,value
0,Switzerland,Western Europe,1,7.587,0.03411,Economy (GDP per Capita),1.39651
1,Iceland,Western Europe,2,7.561,0.04884,Economy (GDP per Capita),1.30232
2,Denmark,Western Europe,3,7.527,0.03328,Economy (GDP per Capita),1.32548
3,Norway,Western Europe,4,7.522,0.03880,Economy (GDP per Capita),1.45900
4,Canada,North America,5,7.427,0.03553,Economy (GDP per Capita),1.32629
...,...,...,...,...,...,...,...
1101,Rwanda,Sub-Saharan Africa,154,3.465,0.03464,Dystopia Residual,0.67042
1102,Benin,Sub-Saharan Africa,155,3.340,0.03656,Dystopia Residual,1.63328
1103,Syria,Middle East and Northern Africa,156,3.006,0.05015,Dystopia Residual,0.32858
1104,Burundi,Sub-Saharan Africa,157,2.905,0.08658,Dystopia Residual,1.83302
1105,Togo,Sub-Saharan Africa,158,2.839,0.06727,Dystopia Residual,1.56726

In [10]:
melt[melt["Country"] == "Pakistan"]

,Country,Region,Happiness Rank,Happiness Score,Standard Error,variable,value
80,Pakistan,Southern Asia,81,5.194,0.03726,Economy (GDP per Capita),0.59543
238,Pakistan,Southern Asia,81,5.194,0.03726,Family,0.41411
396,Pakistan,Southern Asia,81,5.194,0.03726,Health (Life Expectancy),0.51466
554,Pakistan,Southern Asia,81,5.194,0.03726,Freedom,0.12102
712,Pakistan,Southern Asia,81,5.194,0.03726,Trust (Government Corruption),0.10464
870,Pakistan,Southern Asia,81,5.194,0.03726,Generosity,0.33671
1028,Pakistan,Southern Asia,81,5.194,0.03726,Dystopia Residual,3.10709

In [12]:
happiness_2015.shape

(158, 12)

In [13]:
melt.shape

(1106, 7)

In [14]:
len(factors)

7

In [15]:
158*7

1106