In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
page_num = 1
next_button = True
title_rat_avail_stock = []
while next_button:
    base_site = "https://books.toscrape.com/catalogue/category/books/sequential-art_5/index.html"
    response = requests.get(base_site)
    html = response.content
    soup = BeautifulSoup(html,"html.parser")
    next_button = soup.find(class_="next")
    prod = soup.find_all(class_="product_pod")
 
    for i in prod:
        rating = i.find("p").get("class")[1]
        title = i.find("h3").find("a").get("title")
        price = i.find(class_="price_color").text
        stock = i.find(class_="instock availability").text.strip()
    title_rat_avail_stock.append([title,rating,stock,price])
 
    page_num+=1

In [5]:
df = pd.DataFrame(data=title_rat_avail_stock,columns=['Title','Rating','Stock','price'])
df.head(20)

            Title Rating     Stock   price
0   Camp Midnight   Four  In stock  £17.08
1   Camp Midnight   Four  In stock  £17.08
2   Camp Midnight   Four  In stock  £17.08
3   Camp Midnight   Four  In stock  £17.08
4   Camp Midnight   Four  In stock  £17.08
5   Camp Midnight   Four  In stock  £17.08
6   Camp Midnight   Four  In stock  £17.08
7   Camp Midnight   Four  In stock  £17.08
8   Camp Midnight   Four  In stock  £17.08
9   Camp Midnight   Four  In stock  £17.08
10  Camp Midnight   Four  In stock  £17.08
11  Camp Midnight   Four  In stock  £17.08
12  Camp Midnight   Four  In stock  £17.08
13  Camp Midnight   Four  In stock  £17.08
14  Camp Midnight   Four  In stock  £17.08
15  Camp Midnight   Four  In stock  £17.08
16  Camp Midnight   Four  In stock  £17.08
17  Camp Midnight   Four  In stock  £17.08
18  Camp Midnight   Four  In stock  £17.08
19  Camp Midnight   Four  In stock  £17.08