In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Pokemon.csv')

In [29]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [4]:
df.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

In [8]:
df.tail(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
790,714,Noibat,Flying,Dragon,245,40,30,35,45,40,55,6,False
791,715,Noivern,Flying,Dragon,535,85,70,80,97,80,123,6,False
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [13]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [14]:
df.Name

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [15]:
df['Name']

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [16]:
df['Type 1']

0        Grass
1        Grass
2        Grass
3        Grass
4         Fire
        ...
795       Rock
796       Rock
797    Psychic
798    Psychic
799       Fire
Name: Type 1, Length: 800, dtype: object

In [17]:
df.Speed

0       45
1       60
2       80
3       80
4       65
      ...
795     50
796    110
797     70
798     80
799     70
Name: Speed, Length: 800, dtype: int64

In [18]:
df["Speed"]

0       45
1       60
2       80
3       80
4       65
      ...
795     50
796    110
797     70
798     80
799     70
Name: Speed, Length: 800, dtype: int64

In [19]:
df.Name[0:5]

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [26]:
df[['Name','Speed','HP']]

                      Name  Speed  HP
0                Bulbasaur     45  45
1                  Ivysaur     60  60
2                 Venusaur     80  80
3    VenusaurMega Venusaur     80  80
4               Charmander     65  39
..                     ...    ...  ..
795                Diancie     50  50
796    DiancieMega Diancie    110  50
797    HoopaHoopa Confined     70  80
798     HoopaHoopa Unbound     80  80
799              Volcanion     70  80

[800 rows x 3 columns]

In [32]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [33]:
df.iloc[0,5]

45

In [36]:
df.loc[0:4,'Name']

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [37]:
df.iloc[0:4]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False

In [54]:
df.loc[df['Type 1'] == 'Fire']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,505,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,350,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,410,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,500,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,495,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,525,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,309,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,405,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,534,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,250,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,410,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,365,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,310,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,405,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,530,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,305,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,460,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,470,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,309,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,405,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,534,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,540,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,600,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,308,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,528,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,316,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,498,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,315,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,480,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,484,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,307,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,409,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,534,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,382,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,499,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [55]:
# Manullay iterate over a rows

In [58]:
for index,rows in df.iterrows():
    print(index,rows['Type 1'], rows['Speed'])

0 Grass 45
1 Grass 60
2 Grass 80
3 Grass 80
4 Fire 65
5 Fire 80
6 Fire 100
7 Fire 100
8 Fire 100
9 Water 43
10 Water 58
11 Water 78
12 Water 78
13 Bug 45
14 Bug 30
15 Bug 70
16 Bug 50
17 Bug 35
18 Bug 75
19 Bug 145
20 Normal 56
21 Normal 71
22 Normal 101
23 Normal 121
24 Normal 72
25 Normal 97
26 Normal 70
27 Normal 100
28 Poison 55
29 Poison 80
30 Electric 90
31 Electric 110
32 Ground 40
33 Ground 65
34 Poison 41
35 Poison 56
36 Poison 76
37 Poison 50
38 Poison 65
39 Poison 85
40 Fairy 35
41 Fairy 60
42 Fire 65
43 Fire 100
44 Normal 20
45 Normal 45
46 Poison 55
47 Poison 90
48 Grass 30
49 Grass 40
50 Grass 50
51 Bug 25
52 Bug 30
53 Bug 45
54 Bug 90
55 Ground 95
56 Ground 120
57 Normal 90
58 Normal 115
59 Water 55
60 Water 85
61 Fighting 70
62 Fighting 95
63 Fire 60
64 Fire 95
65 Water 90
66 Water 90
67 Water 70
68 Psychic 90
69 Psychic 105
70 Psychic 120
71 Psychic 150
72 Fighting 35
73 Fighting 45
74 Fighting 55
75 Grass 40
76 Grass 55
77 Grass 70
78 Water 70
79 Water 100
80 Rock 20
81 Rock 35
82 Rock 45
83 Fire 90
84 Fire 105
85 Water 15
86 Water 30
87 Water 30
88 Electric 45
89 Electric 70
90 Normal 60
91 Normal 75
92 Normal 100
93 Water 45
94 Water 70
95 Poison 25
96 Poison 50
97 Water 40
98 Water 70
99 Ghost 80
100 Ghost 95
101 Ghost 110
102 Ghost 130
103 Rock 70
104 Psychic 42
105 Psychic 67
106 Water 50
107 Water 75
108 Electric 100
109 Electric 140
110 Grass 40
111 Grass 55
112 Ground 35
113 Ground 45
114 Fighting 87
115 Fighting 76
116 Normal 30
117 Poison 35
118 Poison 60
119 Ground 25
120 Ground 40
121 Normal 50
122 Grass 60
123 Normal 90
124 Normal 100
125 Water 60
126 Water 85
127 Water 63
128 Water 68
129 Water 85
130 Water 115
131 Psychic 90
132 Bug 105
133 Ice 95
134 Electric 105
135 Fire 93
136 Bug 85
137 Bug 105
138 Normal 110
139 Water 80
140 Water 81
141 Water 81
142 Water 60
143 Normal 48
144 Normal 55
145 Water 65
146 Electric 130
147 Fire 65
148 Normal 40
149 Rock 35
150 Rock 55
151 Rock 55
152 Rock 80
153 Rock 130
154 Rock 150
155 Normal 30
156 Ice 85
157 Electric 100
158 Fire 90
159 Dragon 50
160 Dragon 70
161 Dragon 80
162 Psychic 130
163 Psychic 130
164 Psychic 140
165 Psychic 100
166 Grass 45
167 Grass 60
168 Grass 80
169 Fire 65
170 Fire 80
171 Fire 100
172 Water 43
173 Water 58
174 Water 78
175 Normal 20
176 Normal 90
177 Normal 50
178 Normal 70
179 Bug 55
180 Bug 85
181 Bug 30
182 Bug 40
183 Poison 130
184 Water 67
185 Water 67
186 Electric 60
187 Fairy 15
188 Normal 15
189 Fairy 20
190 Fairy 40
191 Psychic 70
192 Psychic 95
193 Electric 35
194 Electric 45
195 Electric 55
196 Electric 45
197 Grass 50
198 Water 40
199 Water 50
200 Rock 30
201 Water 70
202 Grass 50
203 Grass 80
204 Grass 110
205 Normal 85
206 Grass 30
207 Grass 30
208 Bug 95
209 Water 15
210 Water 35
211 Psychic 110
212 Dark 65
213 Dark 91
214 Water 30
215 Ghost 85
216 Psychic 48
217 Psychic 33
218 Normal 85
219 Bug 15
220 Bug 40
221 Normal 45
222 Ground 85
223 Steel 30
224 Steel 30
225 Fairy 30
226 Fairy 45
227 Water 85
228 Bug 65
229 Bug 75
230 Bug 5
231 Bug 85
232 Bug 75
233 Dark 115
234 Normal 40
235 Normal 55
236 Fire 20
237 Fire 30
238 Ice 50
239 Ice 50
240 Water 35
241 Water 65
242 Water 45
243 Ice 75
244 Water 70
245 Steel 70
246 Dark 65
247 Dark 95
248 Dark 115
249 Water 85
250 Ground 40
251 Ground 50
252 Normal 60
253 Normal 85
254 Normal 75
255 Fighting 35
256 Fighting 70
257 Ice 65
258 Electric 95
259 Fire 83
260 Normal 100
261 Normal 55
262 Electric 115
263 Fire 100
264 Water 85
265 Rock 41
266 Rock 51
267 Rock 61
268 Rock 71
269 Psychic 110
270 Fire 90
271 Psychic 100
272 Grass 70
273 Grass 95
274 Grass 120
275 Grass 145
276 Fire 45
277 Fire 55
278 Fire 80
279 Fire 100
280 Water 40
281 Water 50
282 Water 60
283 Water 70
284 Dark 35
285 Dark 70
286 Normal 60
287 Normal 100
288 Bug 20
289 Bug 15
290 Bug 65
291 Bug 15
292 Bug 65
293 Water 30
294 Water 50
295 Water 70
296 Grass 30
297 Grass 60
298 Grass 80
299 Normal 85
300 Normal 125
301 Water 85
302 Water 65
303 Psychic 40
304 Psychic 50
305 Psychic 80
306 Psychic 100
307 Bug 65
308 Bug 60
309 Grass 35
310 Grass 70
311 Normal 30
312 Normal 90
313 Normal 100
314 Bug 40
315 Bug 160
316 Bug 40
317 Normal 28
318 Normal 48
319 Normal 68
320 Fighting 25
321 Fighting 50
322 Normal 20
323 Rock 30
324 Normal 50
325 Normal 70
326 Dark 50
327 Dark 20
328 Steel 50
329 Steel 50
330 Steel 30
331 Steel 40
332 Steel 50
333 Steel 50
334 Fighting 60
335 Fighting 80
336 Fighting 100
337 Electric 65
338 Electric 105
339 Electric 135
340 Electric 95
341 Electric 95
342 Bug 85
343 Bug 85
344 Grass 65
345 Poison 40
346 Poison 55
347 Water 65
348 Water 95
349 Water 105
350 Water 60
351 Water 60
352 Fire 35
353 Fire 40
354 Fire 20
355 Fire 20
356 Psychic 60
357 Psychic 80
358 Normal 60
359 Ground 10
360 Ground 70
361 Ground 100
362 Grass 35
363 Grass 55
364 Normal 50
365 Dragon 80
366 Dragon 80
367 Normal 90
368 Poison 65
369 Rock 70
370 Rock 70
371 Water 60
372 Water 60
373 Water 35
374 Water 55
375 Ground 55
376 Ground 75
377 Rock 23
378 Rock 43
379 Rock 75
380 Rock 45
381 Water 80
382 Water 81
383 Normal 70
384 Normal 40
385 Ghost 45
386 Ghost 65
387 Ghost 75
388 Ghost 25
389 Ghost 25
390 Grass 51
391 Psychic 65
392 Dark 75
393 Dark 115
394 Psychic 23
395 Ice 50
396 Ice 80
397 Ice 100
398 Ice 25
399 Ice 45
400 Ice 65
401 Water 32
402 Water 52
403 Water 52
404 Water 55
405 Water 97
406 Dragon 50
407 Dragon 50
408 Dragon 100
409 Dragon 120
410 Steel 30
411 Steel 50
412 Steel 70
413 Steel 110
414 Rock 50
415 Ice 50
416 Steel 50
417 Dragon 110
418 Dragon 110
419 Dragon 110
420 Dragon 110
421 Water 90
422 Water 90
423 Ground 90
424 Ground 90
425 Dragon 95
426 Dragon 115
427 Steel 100
428 Psychic 150
429 Psychic 150
430 Psychic 90
431 Psychic 180
432 Grass 31
433 Grass 36
434 Grass 56
435 Fire 61
436 Fire 81
437 Fire 108
438 Water 40
439 Water 50
440 Water 60
441 Normal 60
442 Normal 80
443 Normal 100
444 Normal 31
445 Normal 71
446 Bug 25
447 Bug 65
448 Electric 45
449 Electric 60
450 Electric 70
451 Grass 55
452 Grass 90
453 Rock 58
454 Rock 58
455 Rock 30
456 Rock 30
457 Bug 36
458 Bug 36
459 Bug 36
460 Bug 36
461 Bug 66
462 Bug 70
463 Bug 40
464 Electric 95
465 Water 85
466 Water 115
467 Grass 35
468 Grass 85
469 Water 34
470 Water 39
471 Normal 115
472 Ghost 70
473 Ghost 80
474 Normal 85
475 Normal 105
476 Normal 135
477 Ghost 105
478 Dark 71
479 Normal 85
480 Normal 112
481 Psychic 45
482 Poison 74
483 Poison 84
484 Steel 23
485 Steel 33
486 Rock 10
487 Psychic 60
488 Normal 30
489 Normal 91
490 Ghost 35
491 Dragon 42
492 Dragon 82
493 Dragon 102
494 Dragon 92
495 Normal 5
496 Fighting 60
497 Fighting 90
498 Fighting 112
499 Ground 32
500 Ground 47
501 Poison 65
502 Poison 95
503 Poison 50
504 Poison 85
505 Grass 46
506 Water 66
507 Water 91
508 Water 50
509 Grass 40
510 Grass 60
511 Grass 30
512 Dark 125
513 Electric 60
514 Normal 50
515 Ground 40
516 Grass 50
517 Electric 95
518 Fire 83
519 Fairy 80
520 Bug 95
521 Grass 95
522 Ice 65
523 Ground 95
524 Ice 80
525 Normal 90
526 Psychic 80
527 Psychic 110
528 Rock 40
529 Ghost 45
530 Ice 110
531 Electric 91
532 Electric 86
533 Electric 86
534 Electric 86
535 Electric 86
536 Electric 86
537 Psychic 95
538 Psychic 80
539 Psychic 115
540 Steel 90
541 Water 100
542 Fire 77
543 Normal 100
544 Ghost 90
545 Ghost 90
546 Psychic 85
547 Water 80
548 Water 100
549 Dark 125
550 Grass 100
551 Grass 127
552 Normal 120
553 Psychic 100
554 Grass 63
555 Grass 83
556 Grass 113
557 Fire 45
558 Fire 55
559 Fire 65
560 Water 45
561 Water 60
562 Water 70
563 Normal 42
564 Normal 77
565 Normal 55
566 Normal 60
567 Normal 80
568 Dark 66
569 Dark 106
570 Grass 64
571 Grass 101
572 Fire 64
573 Fire 101
574 Water 64
575 Water 101
576 Psychic 24
577 Psychic 29
578 Normal 43
579 Normal 65
580 Normal 93
581 Electric 76
582 Electric 116
583 Rock 15
584 Rock 20
585 Rock 25
586 Psychic 72
587 Psychic 114
588 Ground 68
589 Ground 88
590 Normal 50
591 Normal 50
592 Fighting 35
593 Fighting 40
594 Fighting 45
595 Water 64
596 Water 69
597 Water 74
598 Fighting 45
599 Fighting 85
600 Bug 42
601 Bug 42
602 Bug 92
603 Bug 57
604 Bug 47
605 Bug 112
606 Grass 66
607 Grass 116
608 Grass 30
609 Grass 90
610 Water 98
611 Ground 65
612 Ground 74
613 Ground 92
614 Fire 50
615 Fire 95
616 Fire 55
617 Grass 60
618 Bug 55
619 Bug 45
620 Dark 48
621 Dark 58
622 Psychic 97
623 Ghost 30
624 Ghost 30
625 Water 22
626 Water 32
627 Rock 70
628 Rock 110
629 Poison 65
630 Poison 75
631 Dark 65
632 Dark 105
633 Normal 75
634 Normal 115
635 Psychic 45
636 Psychic 55
637 Psychic 65
638 Psychic 20
639 Psychic 30
640 Psychic 30
641 Water 55
642 Water 98
643 Ice 44
644 Ice 59
645 Ice 79
646 Normal 75
647 Normal 95
648 Electric 103
649 Bug 60
650 Bug 20
651 Grass 15
652 Grass 30
653 Water 40
654 Water 60
655 Water 65
656 Bug 65
657 Bug 108
658 Grass 10
659 Grass 20
660 Steel 30
661 Steel 50
662 Steel 90
663 Electric 60
664 Electric 40
665 Electric 50
666 Psychic 30
667 Psychic 40
668 Ghost 20
669 Ghost 55
670 Ghost 80
671 Dragon 57
672 Dragon 67
673 Dragon 97
674 Ice 40
675 Ice 50
676 Ice 105
677 Bug 25
678 Bug 145
679 Ground 32
680 Fighting 65
681 Fighting 105
682 Dragon 48
683 Ground 35
684 Ground 55
685 Dark 60
686 Dark 70
687 Normal 55
688 Normal 60
689 Normal 80
690 Dark 60
691 Dark 80
692 Fire 65
693 Bug 109
694 Dark 38
695 Dark 58
696 Dark 98
697 Bug 60
698 Bug 100
699 Steel 108
700 Rock 108
701 Grass 108
702 Flying 111

703 Flying 121
704 Electric 111
705 Electric 101
706 Dragon 90
707 Dragon 90
708 Ground 101
709 Ground 91
710 Dragon 95
711 Dragon 95
712 Dragon 95
713 Water 108
714 Water 108
715 Normal 90
716 Normal 128
717 Bug 99
718 Grass 38
719 Grass 57
720 Grass 64
721 Fire 60
722 Fire 73
723 Fire 104
724 Water 71
725 Water 97
726 Water 122
727 Normal 57
728 Normal 78
729 Normal 62
730 Fire 84
731 Fire 126
732 Bug 35
733 Bug 29
734 Bug 89
735 Fire 72
736 Fire 106
737 Fairy 42
738 Fairy 52
739 Fairy 75
740 Grass 52
741 Grass 68
742 Fighting 43
743 Fighting 58
744 Normal 102
745 Psychic 68
746 Psychic 104
747 Psychic 104
748 Steel 28
749 Steel 35
750 Steel 60
751 Steel 60
752 Fairy 23
753 Fairy 29
754 Fairy 49
755 Fairy 72
756 Dark 45
757 Dark 73
758 Rock 50
759 Rock 68
760 Poison 30
761 Poison 44
762 Water 44
763 Water 59
764 Electric 70
765 Electric 109
766 Rock 48
767 Rock 71
768 Rock 46
769 Rock 58
770 Fairy 60
771 Fighting 118
772 Electric 101
773 Rock 50
774 Dragon 40
775 Dragon 60
776 Dragon 80
777 Steel 75
778 Ghost 38
779 Ghost 56
780 Ghost 51
781 Ghost 56
782 Ghost 46
783 Ghost 41
784 Ghost 84
785 Ghost 99
786 Ghost 69
787 Ghost 54
788 Ice 28
789 Ice 28
790 Flying 55
791 Flying 123
792 Fairy 99
793 Dark 99
794 Dragon 95
795 Rock 50
796 Rock 110
797 Psychic 70
798 Psychic 80
799 Fire 70

In [59]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [60]:
df.sort_values('Name')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True

In [66]:
df.sort_values('Name', ascending = False)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False

In [69]:
df.sort_values(['Type 1','HP'],ascending = [1,0])  # 1 means that Type 1 in ascending and HP in desending

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,515,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,550,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,500,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,495,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,325,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,295,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,340,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,200,20,15,20,10,55,80,3,False